project:
  type: website


website:
  navbar:
    left:
      - href: index_2.qmd
        text: Home
      - href: about_2.qmd
        text: About

  page-footer:
    right: "&copy; 2025, Kiana Mohammadinik"
    
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
    
  
execute: 
  freeze: auto
